"""tg clone_rule/version/target + runtime_command

Revision ID: 896f87f95116
Revises: 7077ce051029
Create Date: 2026-09-21 15:21:24.965051

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision = '896f87f95116'
down_revision = '7077ce051029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_clone_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='发送账号ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('mode', sa.String(length=16), nullable=False, comment='模式(copy/forward)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('current_version', sa.Integer(), nullable=False, comment='当前已发布版本号(0=未发布)'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='规则状态(draft/published/disabled)'),
    sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'deleted', name='uk_tg_rule_name_deleted'),
    sa.UniqueConstraint('uuid'),
    comment='TG 平台 Clone 规则表'
    )
    op.create_index(op.f('ix_tg_clone_rule_account_id'), 'tg_clone_rule', ['account_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_rule_id'), 'tg_clone_rule', ['id'], unique=True)
    op.create_index(op.f('ix_tg_clone_rule_project_id'), 'tg_clone_rule', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_rule_status'), 'tg_clone_rule', ['status'], unique=False)
    op.create_index(op.f('ix_tg_clone_rule_tenant_id'), 'tg_clone_rule', ['tenant_id'], unique=False)
    op.create_table('tg_clone_rule_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False, comment='规则ID'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号(递增)'),
    sa.Column('snapshot', sa.JSON(), nullable=False, comment='发布快照{rule,targets,filters}'),
    sa.Column('published_by', sa.BigInteger(), nullable=False, comment='发布人系统用户ID'),
    sa.Column('published_at', backend.common.model.TimeZone(timezone=True), nullable=False, comment='发布时间'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uk_tg_rule_version'),
    sa.UniqueConstraint('uuid'),
    comment='TG 平台 Clone 规则版本表'
    )
    op.create_index(op.f('ix_tg_clone_rule_version_id'), 'tg_clone_rule_version', ['id'], unique=True)
    op.create_index(op.f('ix_tg_clone_rule_version_project_id'), 'tg_clone_rule_version', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_rule_version_rule_id'), 'tg_clone_rule_version', ['rule_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_rule_version_tenant_id'), 'tg_clone_rule_version', ['tenant_id'], unique=False)
    op.create_table('tg_clone_target',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False, comment='规则ID'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('route_id', sa.String(length=64), nullable=False, comment='稳定路由ID(跨版本不变)'),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False, comment='源 chat ID'),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False, comment='目标 chat ID'),
    sa.Column('source_topic_id', sa.BigInteger(), nullable=True, comment='源 topic'),
    sa.Column('target_topic_id', sa.BigInteger(), nullable=True, comment='目标 topic'),
    sa.Column('filters', sa.JSON(), nullable=True, comment='过滤条件{keywords,media,...}'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态(active/retired)'),
    sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id'),
    sa.UniqueConstraint('rule_id', 'source_chat_id', 'source_topic_id', 'deleted', name='uk_tg_target_src_deleted'),
    sa.UniqueConstraint('uuid'),
    comment='TG 平台 Clone 目标表'
    )
    op.create_index(op.f('ix_tg_clone_target_id'), 'tg_clone_target', ['id'], unique=True)
    op.create_index(op.f('ix_tg_clone_target_project_id'), 'tg_clone_target', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_target_rule_id'), 'tg_clone_target', ['rule_id'], unique=False)
    op.create_index(op.f('ix_tg_clone_target_status'), 'tg_clone_target', ['status'], unique=False)
    op.create_index(op.f('ix_tg_clone_target_tenant_id'), 'tg_clone_target', ['tenant_id'], unique=False)
    op.create_table('tg_runtime_command',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False, comment='命令去重键(重放幂等)'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='账号ID'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='命令类型(StartAccount/StopAccount/ReloadConfig/SyncChats/ReconcileSource/CancelJob)'),
    sa.Column('issued_by', sa.BigInteger(), nullable=False, comment='下发人系统用户ID'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='命令参数'),
    sa.Column('expected_generation', sa.BigInteger(), nullable=True, comment='期望的账号租约代次'),
    sa.Column('deadline', backend.common.model.TimeZone(timezone=True), nullable=True, comment='过期时间'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路 ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态(pending/acknowledged/done/rejected/duplicate)'),
    sa.Column('result', sa.String(length=512), nullable=True, comment='执行结果摘要'),
    sa.Column('acked_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='确认时间'),
    sa.Column('finished_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key'),
    sa.UniqueConstraint('uuid'),
    comment='TG 平台运行时命令表'
    )
    op.create_index(op.f('ix_tg_runtime_command_account_id'), 'tg_runtime_command', ['account_id'], unique=False)
    op.create_index(op.f('ix_tg_runtime_command_id'), 'tg_runtime_command', ['id'], unique=True)
    op.create_index(op.f('ix_tg_runtime_command_project_id'), 'tg_runtime_command', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_runtime_command_status'), 'tg_runtime_command', ['status'], unique=False)
    op.create_index(op.f('ix_tg_runtime_command_tenant_id'), 'tg_runtime_command', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tg_runtime_command_type'), 'tg_runtime_command', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_runtime_command_type'), table_name='tg_runtime_command')
    op.drop_index(op.f('ix_tg_runtime_command_tenant_id'), table_name='tg_runtime_command')
    op.drop_index(op.f('ix_tg_runtime_command_status'), table_name='tg_runtime_command')
    op.drop_index(op.f('ix_tg_runtime_command_project_id'), table_name='tg_runtime_command')
    op.drop_index(op.f('ix_tg_runtime_command_id'), table_name='tg_runtime_command')
    op.drop_index(op.f('ix_tg_runtime_command_account_id'), table_name='tg_runtime_command')
    op.drop_table('tg_runtime_command')
    op.drop_index(op.f('ix_tg_clone_target_tenant_id'), table_name='tg_clone_target')
    op.drop_index(op.f('ix_tg_clone_target_status'), table_name='tg_clone_target')
    op.drop_index(op.f('ix_tg_clone_target_rule_id'), table_name='tg_clone_target')
    op.drop_index(op.f('ix_tg_clone_target_project_id'), table_name='tg_clone_target')
    op.drop_index(op.f('ix_tg_clone_target_id'), table_name='tg_clone_target')
    op.drop_table('tg_clone_target')
    op.drop_index(op.f('ix_tg_clone_rule_version_tenant_id'), table_name='tg_clone_rule_version')
    op.drop_index(op.f('ix_tg_clone_rule_version_rule_id'), table_name='tg_clone_rule_version')
    op.drop_index(op.f('ix_tg_clone_rule_version_project_id'), table_name='tg_clone_rule_version')
    op.drop_index(op.f('ix_tg_clone_rule_version_id'), table_name='tg_clone_rule_version')
    op.drop_table('tg_clone_rule_version')
    op.drop_index(op.f('ix_tg_clone_rule_tenant_id'), table_name='tg_clone_rule')
    op.drop_index(op.f('ix_tg_clone_rule_status'), table_name='tg_clone_rule')
    op.drop_index(op.f('ix_tg_clone_rule_project_id'), table_name='tg_clone_rule')
    op.drop_index(op.f('ix_tg_clone_rule_id'), table_name='tg_clone_rule')
    op.drop_index(op.f('ix_tg_clone_rule_account_id'), table_name='tg_clone_rule')
    op.drop_table('tg_clone_rule')
    # ### end Alembic commands ###
