"""tg_ai_binding_conversation_run_callback

Revision ID: fd6cc8a2cfc9
Revises: abe62242e60a
Create Date: 2026-09-21 16:13:52.364266

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision = 'fd6cc8a2cfc9'
down_revision = 'abe62242e60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_ai_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='默认发送账号ID'),
    sa.Column('bot_uuid', sa.String(length=64), nullable=False, comment='LangBot bot UUID'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='LangBot 内部地址,如 http://langbot:5300'),
    sa.Column('inbound_secret_ref', sa.String(length=128), nullable=False, comment='入站签名密钥引用 env:NAME'),
    sa.Column('outbound_secret_ref', sa.String(length=128), nullable=False, comment='回调验签密钥引用 env:NAME'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    comment='TG AI LangBot 绑定表'
    )
    op.create_index(op.f('ix_tg_ai_binding_account_id'), 'tg_ai_binding', ['account_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_binding_bot_uuid'), 'tg_ai_binding', ['bot_uuid'], unique=False)
    op.create_index(op.f('ix_tg_ai_binding_id'), 'tg_ai_binding', ['id'], unique=True)
    op.create_index(op.f('ix_tg_ai_binding_project_id'), 'tg_ai_binding', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_binding_status'), 'tg_ai_binding', ['status'], unique=False)
    op.create_index(op.f('ix_tg_ai_binding_tenant_id'), 'tg_ai_binding', ['tenant_id'], unique=False)
    op.create_table('tg_ai_conversation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='账号ID'),
    sa.Column('binding_id', sa.BigInteger(), nullable=False, comment='绑定ID'),
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='群 chat ID'),
    sa.Column('session_id', sa.String(length=96), nullable=False, comment='LangBot session_id'),
    sa.Column('topic_id', sa.BigInteger(), nullable=True, comment='topic'),
    sa.Column('agent_key', sa.String(length=64), nullable=True, comment='Agent 键'),
    sa.Column('context_epoch', sa.Integer(), nullable=False, comment='上下文代次(重建时递增)'),
    sa.Column('context_messages', sa.JSON(), nullable=False, comment='有界已发送上下文'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open/locked(有未完成 run)'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['binding_id'], ['tg_ai_binding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'chat_id', 'topic_id', 'agent_key', 'context_epoch', name='uq_tg_ai_conv_scope_epoch'),
    sa.UniqueConstraint('uuid'),
    comment='TG AI 会话表'
    )
    op.create_index(op.f('ix_tg_ai_conversation_account_id'), 'tg_ai_conversation', ['account_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_conversation_binding_id'), 'tg_ai_conversation', ['binding_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_conversation_chat_id'), 'tg_ai_conversation', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_conversation_id'), 'tg_ai_conversation', ['id'], unique=True)
    op.create_index(op.f('ix_tg_ai_conversation_project_id'), 'tg_ai_conversation', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_conversation_session_id'), 'tg_ai_conversation', ['session_id'], unique=True)
    op.create_index(op.f('ix_tg_ai_conversation_status'), 'tg_ai_conversation', ['status'], unique=False)
    op.create_index(op.f('ix_tg_ai_conversation_tenant_id'), 'tg_ai_conversation', ['tenant_id'], unique=False)
    op.create_table('tg_ai_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='会话ID'),
    sa.Column('session_id', sa.String(length=96), nullable=False, comment='LangBot session_id'),
    sa.Column('trigger_source', sa.JSON(), nullable=False, comment='触发来源消息集合(合并须记录)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/dispatched/running/completed/incomplete/failed/cancelled'),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True, comment='产出候选'),
    sa.Column('accepted_message_id', sa.String(length=64), nullable=True, comment='LangBot 202 回执 in_xxx'),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('deadline', backend.common.model.TimeZone(timezone=True), nullable=True, comment='回调截止时间'),
    sa.Column('expected_seq', sa.Integer(), nullable=False, comment='期望下一个 sequence'),
    sa.Column('context_window', sa.JSON(), nullable=True, comment='{max_messages, injected_count, strategy}'),
    sa.Column('usage', sa.JSON(), nullable=True, comment='token/费用结算(§9.5)'),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('completed_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['candidate_id'], ['tg_reply_candidate.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['tg_ai_conversation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('uuid'),
    comment='TG AI 运行表'
    )
    op.create_index(op.f('ix_tg_ai_run_conversation_id'), 'tg_ai_run', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_run_id'), 'tg_ai_run', ['id'], unique=True)
    op.create_index(op.f('ix_tg_ai_run_project_id'), 'tg_ai_run', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_run_session_id'), 'tg_ai_run', ['session_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_run_status'), 'tg_ai_run', ['status'], unique=False)
    op.create_index(op.f('ix_tg_ai_run_tenant_id'), 'tg_ai_run', ['tenant_id'], unique=False)
    op.create_index('uq_tg_ai_run_active_session', 'tg_ai_run', ['session_id'], unique=True, postgresql_where=sa.text("status IN ('pending','dispatched','running')"))
    op.create_table('tg_ai_callback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('binding_id', sa.BigInteger(), nullable=False, comment='绑定ID'),
    sa.Column('session_id', sa.String(length=96), nullable=False),
    sa.Column('reply_to', sa.String(length=64), nullable=False, comment='对应 inbound accepted_message_id'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='会话内单调序号'),
    sa.Column('is_final', sa.Boolean(), nullable=False, comment='turn 结束'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='原始回调体'),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False, comment='body sha256'),
    sa.Column('received_at', backend.common.model.TimeZone(timezone=True), nullable=False, comment='接收时间'),
    sa.Column('ai_run_id', sa.BigInteger(), nullable=True, comment='关联 run;reply_to 未匹配时为空'),
    sa.Column('link_status', sa.String(length=20), nullable=False, comment='linked/pending_link/orphan'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['ai_run_id'], ['tg_ai_run.id'], ),
    sa.ForeignKeyConstraint(['binding_id'], ['tg_ai_binding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_id', 'session_id', 'reply_to', 'sequence', name='uq_tg_ai_callback_seq'),
    sa.UniqueConstraint('uuid'),
    comment='TG AI 回调表'
    )
    op.create_index(op.f('ix_tg_ai_callback_ai_run_id'), 'tg_ai_callback', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_callback_binding_id'), 'tg_ai_callback', ['binding_id'], unique=False)
    op.create_index(op.f('ix_tg_ai_callback_id'), 'tg_ai_callback', ['id'], unique=True)
    op.create_index(op.f('ix_tg_ai_callback_link_status'), 'tg_ai_callback', ['link_status'], unique=False)
    op.create_index(op.f('ix_tg_ai_callback_session_id'), 'tg_ai_callback', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_ai_callback_session_id'), table_name='tg_ai_callback')
    op.drop_index(op.f('ix_tg_ai_callback_link_status'), table_name='tg_ai_callback')
    op.drop_index(op.f('ix_tg_ai_callback_id'), table_name='tg_ai_callback')
    op.drop_index(op.f('ix_tg_ai_callback_binding_id'), table_name='tg_ai_callback')
    op.drop_index(op.f('ix_tg_ai_callback_ai_run_id'), table_name='tg_ai_callback')
    op.drop_table('tg_ai_callback')
    op.drop_index('uq_tg_ai_run_active_session', table_name='tg_ai_run', postgresql_where=sa.text("status IN ('pending','dispatched','running')"))
    op.drop_index(op.f('ix_tg_ai_run_tenant_id'), table_name='tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_run_status'), table_name='tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_run_session_id'), table_name='tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_run_project_id'), table_name='tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_run_id'), table_name='tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_run_conversation_id'), table_name='tg_ai_run')
    op.drop_table('tg_ai_run')
    op.drop_index(op.f('ix_tg_ai_conversation_tenant_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_status'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_session_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_project_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_chat_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_binding_id'), table_name='tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_conversation_account_id'), table_name='tg_ai_conversation')
    op.drop_table('tg_ai_conversation')
    op.drop_index(op.f('ix_tg_ai_binding_tenant_id'), table_name='tg_ai_binding')
    op.drop_index(op.f('ix_tg_ai_binding_status'), table_name='tg_ai_binding')
    op.drop_index(op.f('ix_tg_ai_binding_project_id'), table_name='tg_ai_binding')
    op.drop_index(op.f('ix_tg_ai_binding_id'), table_name='tg_ai_binding')
    op.drop_index(op.f('ix_tg_ai_binding_bot_uuid'), table_name='tg_ai_binding')
    op.drop_index(op.f('ix_tg_ai_binding_account_id'), table_name='tg_ai_binding')
    op.drop_table('tg_ai_binding')
    # ### end Alembic commands ###
