"""tg tenant/project/membership

Revision ID: ddbe2918b0ce
Revises:
Create Date: 2026-09-21 14:51:48.222087

"""

import sqlalchemy as sa

from alembic import op

import backend.common.model

# revision identifiers, used by Alembic.
revision = 'ddbe2918b0ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tg_membership',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
        sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='系统用户ID'),
        sa.Column('role', sa.String(length=32), nullable=False, comment='角色(owner/admin/member)'),
        sa.Column('status', sa.Integer(), nullable=False, comment='成员状态(0停用 1正常)'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'project_id', 'user_id', 'deleted', name='uk_tg_membership_scope_deleted'),
        sa.UniqueConstraint('uuid'),
        comment='TG 平台成员表',
    )
    op.create_index(op.f('ix_tg_membership_id'), 'tg_membership', ['id'], unique=True)
    op.create_index(op.f('ix_tg_membership_project_id'), 'tg_membership', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_membership_tenant_id'), 'tg_membership', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tg_membership_user_id'), 'tg_membership', ['user_id'], unique=False)
    op.create_table(
        'tg_project',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
        sa.Column('name', sa.String(length=128), nullable=False, comment='项目名称'),
        sa.Column('status', sa.Integer(), nullable=False, comment='项目状态(0停用 1正常)'),
        sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', 'deleted', name='uk_tg_project_tenant_name_deleted'),
        sa.UniqueConstraint('uuid'),
        comment='TG 平台项目表',
    )
    op.create_index(op.f('ix_tg_project_id'), 'tg_project', ['id'], unique=True)
    op.create_index(op.f('ix_tg_project_status'), 'tg_project', ['status'], unique=False)
    op.create_index(op.f('ix_tg_project_tenant_id'), 'tg_project', ['tenant_id'], unique=False)
    op.create_table(
        'tg_tenant',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
        sa.Column('status', sa.Integer(), nullable=False, comment='租户状态(0停用 1正常)'),
        sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'deleted', name='uk_tg_tenant_name_deleted'),
        sa.UniqueConstraint('uuid'),
        comment='TG 平台租户表',
    )
    op.create_index(op.f('ix_tg_tenant_id'), 'tg_tenant', ['id'], unique=True)
    op.create_index(op.f('ix_tg_tenant_name'), 'tg_tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tg_tenant_status'), 'tg_tenant', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_tenant_status'), table_name='tg_tenant')
    op.drop_index(op.f('ix_tg_tenant_name'), table_name='tg_tenant')
    op.drop_index(op.f('ix_tg_tenant_id'), table_name='tg_tenant')
    op.drop_table('tg_tenant')
    op.drop_index(op.f('ix_tg_project_tenant_id'), table_name='tg_project')
    op.drop_index(op.f('ix_tg_project_status'), table_name='tg_project')
    op.drop_index(op.f('ix_tg_project_id'), table_name='tg_project')
    op.drop_table('tg_project')
    op.drop_index(op.f('ix_tg_membership_user_id'), table_name='tg_membership')
    op.drop_index(op.f('ix_tg_membership_tenant_id'), table_name='tg_membership')
    op.drop_index(op.f('ix_tg_membership_project_id'), table_name='tg_membership')
    op.drop_index(op.f('ix_tg_membership_id'), table_name='tg_membership')
    op.drop_table('tg_membership')
    # ### end Alembic commands ###
