"""tg delivery mirror + reply_candidate/approval

Revision ID: abe62242e60a
Revises: 896f87f95116
Create Date: 2026-09-21 15:37:15.880863

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision = 'abe62242e60a'
down_revision = '896f87f95116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='租户 uuid'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目 uuid'),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False, comment='业务动作幂等键'),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='任务类型'),
    sa.Column('route_id', sa.String(length=64), nullable=False, comment='目标路由 ID'),
    sa.Column('rule_id', sa.String(length=64), nullable=False, comment='规则标识'),
    sa.Column('rule_version', sa.Integer(), nullable=False, comment='规则版本'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='账号 uuid'),
    sa.Column('source_scope', sa.String(length=200), nullable=False, comment='源作用域'),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False, comment='源 chat'),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False, comment='源消息 ID'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='源消息版本'),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False, comment='目标 chat'),
    sa.Column('target_topic_id', sa.BigInteger(), nullable=True, comment='目标 topic'),
    sa.Column('mode', sa.String(length=10), nullable=False, comment='copy/forward'),
    sa.Column('payload_ref', sa.String(length=500), nullable=True, comment='载荷引用'),
    sa.Column('payload_hash', sa.String(length=128), nullable=True, comment='载荷 hash'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='是否需要审批'),
    sa.Column('reply_to_target_message_id', sa.BigInteger(), nullable=True),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='投递状态'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='已尝试次数'),
    sa.Column('next_attempt_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='下次可执行时间'),
    sa.Column('flood_wait_until', backend.common.model.TimeZone(timezone=True), nullable=True, comment='限流截止'),
    sa.Column('last_error_class', sa.String(length=40), nullable=True, comment='最近错误分级'),
    sa.Column('created_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    comment='TG 投递任务表(与 runtime 共享)'
    )
    op.create_index(op.f('ix_delivery_job_account_id'), 'delivery_job', ['account_id'], unique=False)
    op.create_index(op.f('ix_delivery_job_project_id'), 'delivery_job', ['project_id'], unique=False)
    op.create_index(op.f('ix_delivery_job_route_id'), 'delivery_job', ['route_id'], unique=False)
    op.create_index(op.f('ix_delivery_job_status'), 'delivery_job', ['status'], unique=False)
    op.create_index(op.f('ix_delivery_job_tenant_id'), 'delivery_job', ['tenant_id'], unique=False)
    op.create_table('message_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='租户 uuid'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目 uuid'),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False, comment='目标路由 ID'),
    sa.Column('rule_version_at_create', sa.Integer(), nullable=False),
    sa.Column('source_scope', sa.String(length=200), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('source_album_id', sa.BigInteger(), nullable=True),
    sa.Column('source_member_index', sa.Integer(), nullable=True),
    sa.Column('sender_account_id', sa.String(length=36), nullable=False, comment='发送账号 uuid'),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('target_topic_id', sa.BigInteger(), nullable=True),
    sa.Column('target_message_id', sa.BigInteger(), nullable=False),
    sa.Column('output_part_index', sa.Integer(), nullable=False),
    sa.Column('last_applied_revision', sa.Integer(), nullable=False),
    sa.Column('delivery_job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('created_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('updated_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='TG 消息映射表'
    )
    op.create_index(op.f('ix_message_map_project_id'), 'message_map', ['project_id'], unique=False)
    op.create_index(op.f('ix_message_map_route_id'), 'message_map', ['route_id'], unique=False)
    op.create_index(op.f('ix_message_map_source_message_id'), 'message_map', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_message_map_target_chat_id'), 'message_map', ['target_chat_id'], unique=False)
    op.create_index(op.f('ix_message_map_target_message_id'), 'message_map', ['target_message_id'], unique=False)
    op.create_index(op.f('ix_message_map_tenant_id'), 'message_map', ['tenant_id'], unique=False)
    op.create_table('tg_reply_candidate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='账号ID'),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False, comment='目标 chat'),
    sa.Column('content', sa.Text(), nullable=False, comment='规范化文本内容'),
    sa.Column('content_hash', sa.String(length=128), nullable=False, comment='内容 hash'),
    sa.Column('expires_at', backend.common.model.TimeZone(timezone=True), nullable=False, comment='候选过期时间'),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True, comment='AI 运行标识'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='关联规则ID'),
    sa.Column('target_topic_id', sa.BigInteger(), nullable=True, comment='目标 topic'),
    sa.Column('reply_to_source_id', sa.BigInteger(), nullable=True, comment='回复目标'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件版本与校验值'),
    sa.Column('version', sa.Integer(), nullable=False, comment='候选版本(内容变化=新候选)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态(pending/approved/rejected/expired/consumed/superseded)'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    comment='TG 回复候选表'
    )
    op.create_index(op.f('ix_tg_reply_candidate_account_id'), 'tg_reply_candidate', ['account_id'], unique=False)
    op.create_index(op.f('ix_tg_reply_candidate_content_hash'), 'tg_reply_candidate', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tg_reply_candidate_id'), 'tg_reply_candidate', ['id'], unique=True)
    op.create_index(op.f('ix_tg_reply_candidate_project_id'), 'tg_reply_candidate', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_reply_candidate_status'), 'tg_reply_candidate', ['status'], unique=False)
    op.create_index(op.f('ix_tg_reply_candidate_tenant_id'), 'tg_reply_candidate', ['tenant_id'], unique=False)
    op.create_table('delivery_attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_generation', sa.Integer(), nullable=False),
    sa.Column('started_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('finished_at', backend.common.model.TimeZone(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=30), nullable=True),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.Column('request_ref', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['delivery_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='TG 投递尝试表(append-only)'
    )
    op.create_index(op.f('ix_delivery_attempt_job_id'), 'delivery_attempt', ['job_id'], unique=False)
    op.create_table('tg_approval',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_version', sa.Integer(), nullable=False, comment='绑定的候选版本'),
    sa.Column('content_hash', sa.String(length=128), nullable=False, comment='绑定的内容 hash'),
    sa.Column('expires_at', backend.common.model.TimeZone(timezone=True), nullable=False, comment='审批有效期(与候选一致)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态(pending/approved/rejected/expired)'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('decided_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='决定时间'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='拒绝/备注原因'),
    sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'),
    sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['candidate_id'], ['tg_reply_candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    comment='TG 审批表'
    )
    op.create_index(op.f('ix_tg_approval_candidate_id'), 'tg_approval', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_tg_approval_id'), 'tg_approval', ['id'], unique=True)
    op.create_index(op.f('ix_tg_approval_project_id'), 'tg_approval', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_approval_status'), 'tg_approval', ['status'], unique=False)
    op.create_index(op.f('ix_tg_approval_tenant_id'), 'tg_approval', ['tenant_id'], unique=False)
    op.alter_column('tg_runtime_command', 'dedup_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_comment='命令去重键(重放幂等)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_runtime_command', 'dedup_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_comment='命令去重键(重放幂等)',
               existing_nullable=False)
    op.drop_index(op.f('ix_tg_approval_tenant_id'), table_name='tg_approval')
    op.drop_index(op.f('ix_tg_approval_status'), table_name='tg_approval')
    op.drop_index(op.f('ix_tg_approval_project_id'), table_name='tg_approval')
    op.drop_index(op.f('ix_tg_approval_id'), table_name='tg_approval')
    op.drop_index(op.f('ix_tg_approval_candidate_id'), table_name='tg_approval')
    op.drop_table('tg_approval')
    op.drop_index(op.f('ix_delivery_attempt_job_id'), table_name='delivery_attempt')
    op.drop_table('delivery_attempt')
    op.drop_index(op.f('ix_tg_reply_candidate_tenant_id'), table_name='tg_reply_candidate')
    op.drop_index(op.f('ix_tg_reply_candidate_status'), table_name='tg_reply_candidate')
    op.drop_index(op.f('ix_tg_reply_candidate_project_id'), table_name='tg_reply_candidate')
    op.drop_index(op.f('ix_tg_reply_candidate_id'), table_name='tg_reply_candidate')
    op.drop_index(op.f('ix_tg_reply_candidate_content_hash'), table_name='tg_reply_candidate')
    op.drop_index(op.f('ix_tg_reply_candidate_account_id'), table_name='tg_reply_candidate')
    op.drop_table('tg_reply_candidate')
    op.drop_index(op.f('ix_message_map_tenant_id'), table_name='message_map')
    op.drop_index(op.f('ix_message_map_target_message_id'), table_name='message_map')
    op.drop_index(op.f('ix_message_map_target_chat_id'), table_name='message_map')
    op.drop_index(op.f('ix_message_map_source_message_id'), table_name='message_map')
    op.drop_index(op.f('ix_message_map_route_id'), table_name='message_map')
    op.drop_index(op.f('ix_message_map_project_id'), table_name='message_map')
    op.drop_table('message_map')
    op.drop_index(op.f('ix_delivery_job_tenant_id'), table_name='delivery_job')
    op.drop_index(op.f('ix_delivery_job_status'), table_name='delivery_job')
    op.drop_index(op.f('ix_delivery_job_route_id'), table_name='delivery_job')
    op.drop_index(op.f('ix_delivery_job_project_id'), table_name='delivery_job')
    op.drop_index(op.f('ix_delivery_job_account_id'), table_name='delivery_job')
    op.drop_table('delivery_job')
    # ### end Alembic commands ###
