"""tg telegram_account + import_batch

Revision ID: 7077ce051029
Revises: ddbe2918b0ce
Create Date: 2026-09-21 15:07:40.354263

"""

import sqlalchemy as sa

from alembic import op

import backend.common.model

# revision identifiers, used by Alembic.
revision = '7077ce051029'
down_revision = 'ddbe2918b0ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tg_import_batch',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
        sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
        sa.Column('operator_id', sa.BigInteger(), nullable=False, comment='操作者系统用户ID'),
        sa.Column('filename', sa.String(length=256), nullable=False, comment='上传文件名'),
        sa.Column('file_sha256', sa.String(length=64), nullable=False, comment='上传文件 SHA-256'),
        sa.Column('total', sa.Integer(), nullable=False, comment='包内 session 总数'),
        sa.Column('verified', sa.Integer(), nullable=False, comment='验证通过数'),
        sa.Column('failed', sa.Integer(), nullable=False, comment='验证失败数'),
        sa.Column('status', sa.String(length=32), nullable=False, comment='批次状态(processing/completed/failed)'),
        sa.Column(
            'detail',
            sa.JSON(),
            nullable=True,
            comment='逐项结果[{key,status,user_id,username,two_fa,spamblock,detail}]',
        ),
        sa.Column('finished_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='批次完成时间'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uuid'),
        comment='TG 平台 Session 导入批次表',
    )
    op.create_index(op.f('ix_tg_import_batch_id'), 'tg_import_batch', ['id'], unique=True)
    op.create_index(op.f('ix_tg_import_batch_operator_id'), 'tg_import_batch', ['operator_id'], unique=False)
    op.create_index(op.f('ix_tg_import_batch_project_id'), 'tg_import_batch', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_import_batch_status'), 'tg_import_batch', ['status'], unique=False)
    op.create_index(op.f('ix_tg_import_batch_tenant_id'), 'tg_import_batch', ['tenant_id'], unique=False)
    op.create_table(
        'tg_telegram_account',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
        sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目ID'),
        sa.Column('import_batch_id', sa.BigInteger(), nullable=True, comment='导入批次ID'),
        sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
        sa.Column('telegram_user_id', sa.BigInteger(), nullable=True, comment='Telegram 用户ID'),
        sa.Column('username', sa.String(length=64), nullable=True, comment='Telegram 用户名'),
        sa.Column('secret_ref', sa.String(length=256), nullable=True, comment='加密会话引用(会话密文不落此表)'),
        sa.Column('desired_status', sa.String(length=32), nullable=False, comment='期望状态(stopped/running)'),
        sa.Column(
            'observed_status',
            sa.String(length=32),
            nullable=False,
            comment='观测状态(imported_quarantine/verified/active/reauth_required/revoked/disabled)',
        ),
        sa.Column(
            'last_seen_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='最近一次在线探测时间'
        ),
        sa.Column('last_error', sa.String(length=512), nullable=True, comment='最近错误摘要'),
        sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_user_id', 'deleted', name='uk_tg_account_tguser_deleted'),
        sa.UniqueConstraint('uuid'),
        comment='TG 平台 Telegram 账号表',
    )
    op.create_index(op.f('ix_tg_telegram_account_id'), 'tg_telegram_account', ['id'], unique=True)
    op.create_index(
        op.f('ix_tg_telegram_account_import_batch_id'), 'tg_telegram_account', ['import_batch_id'], unique=False
    )
    op.create_index(
        op.f('ix_tg_telegram_account_observed_status'), 'tg_telegram_account', ['observed_status'], unique=False
    )
    op.create_index(op.f('ix_tg_telegram_account_project_id'), 'tg_telegram_account', ['project_id'], unique=False)
    op.create_index(op.f('ix_tg_telegram_account_tenant_id'), 'tg_telegram_account', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_telegram_account_tenant_id'), table_name='tg_telegram_account')
    op.drop_index(op.f('ix_tg_telegram_account_project_id'), table_name='tg_telegram_account')
    op.drop_index(op.f('ix_tg_telegram_account_observed_status'), table_name='tg_telegram_account')
    op.drop_index(op.f('ix_tg_telegram_account_import_batch_id'), table_name='tg_telegram_account')
    op.drop_index(op.f('ix_tg_telegram_account_id'), table_name='tg_telegram_account')
    op.drop_table('tg_telegram_account')
    op.drop_index(op.f('ix_tg_import_batch_tenant_id'), table_name='tg_import_batch')
    op.drop_index(op.f('ix_tg_import_batch_status'), table_name='tg_import_batch')
    op.drop_index(op.f('ix_tg_import_batch_project_id'), table_name='tg_import_batch')
    op.drop_index(op.f('ix_tg_import_batch_operator_id'), table_name='tg_import_batch')
    op.drop_index(op.f('ix_tg_import_batch_id'), table_name='tg_import_batch')
    op.drop_table('tg_import_batch')
    # ### end Alembic commands ###
