/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  tg_account: () => import("@/views/tg/account/index.vue"),
  tg_approval: () => import("@/views/tg/approval/index.vue"),
  tg_command: () => import("@/views/tg/command/index.vue"),
  tg_delivery: () => import("@/views/tg/delivery/index.vue"),
  tg_import: () => import("@/views/tg/import/index.vue"),
  tg_project: () => import("@/views/tg/project/index.vue"),
  tg_rule: () => import("@/views/tg/rule/index.vue"),
  tg_tenant: () => import("@/views/tg/tenant/index.vue"),
};
