/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'tg',
    path: '/tg',
    component: 'layout.base',
    meta: {
      title: 'tg',
      i18nKey: 'route.tg'
    },
    children: [
      {
        name: 'tg_account',
        path: '/tg/account',
        component: 'view.tg_account',
        meta: {
          title: 'tg_account',
          i18nKey: 'route.tg_account'
        }
      },
      {
        name: 'tg_approval',
        path: '/tg/approval',
        component: 'view.tg_approval',
        meta: {
          title: 'tg_approval',
          i18nKey: 'route.tg_approval'
        }
      },
      {
        name: 'tg_command',
        path: '/tg/command',
        component: 'view.tg_command',
        meta: {
          title: 'tg_command',
          i18nKey: 'route.tg_command'
        }
      },
      {
        name: 'tg_delivery',
        path: '/tg/delivery',
        component: 'view.tg_delivery',
        meta: {
          title: 'tg_delivery',
          i18nKey: 'route.tg_delivery'
        }
      },
      {
        name: 'tg_import',
        path: '/tg/import',
        component: 'view.tg_import',
        meta: {
          title: 'tg_import',
          i18nKey: 'route.tg_import'
        }
      },
      {
        name: 'tg_project',
        path: '/tg/project',
        component: 'view.tg_project',
        meta: {
          title: 'tg_project',
          i18nKey: 'route.tg_project'
        }
      },
      {
        name: 'tg_rule',
        path: '/tg/rule',
        component: 'view.tg_rule',
        meta: {
          title: 'tg_rule',
          i18nKey: 'route.tg_rule'
        }
      },
      {
        name: 'tg_tenant',
        path: '/tg/tenant',
        component: 'view.tg_tenant',
        meta: {
          title: 'tg_tenant',
          i18nKey: 'route.tg_tenant'
        }
      }
    ]
  }
];
